version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/usr/share/nginx/html
      - ./certs:/etc/nginx/ssl
      - ./Docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Docker/000-default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Docker/default-ssl.conf:/etc/nginx/conf.d/default-ssl.conf:ro
    depends_on:
      - php
      - db
      - mongo
    environment:
      - SERVER_NAME=api.meuprojeto.com.br

  php:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    container_name: php-back
    volumes:
      - ./:/usr/share/nginx/html
    environment:
      - SERVER_NAME=api.meuprojeto.com.br

  db:
    container_name: mysql8-back
    image: mysql:8.0
    command: >
      mysqld --default-authentication-plugin=mysql_native_password
             --character-set-server=utf8mb4
             --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: ProjetoUser
      MYSQL_PASSWORD: '*minhanov@Senha321*'
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3312:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./Docker/my.cnf:/etc/mysql/conf.d/my.cnf

  mongo:
    container_name: mongodb-back
    image: mongo:latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ProjetoUser
      MONGO_INITDB_ROOT_PASSWORD: '*minhanov@Senha321*'
      MONGO_INITDB_DATABASE: projeto
    ports:
      - "27019:27017"
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/ssl:/etc/ssl

volumes:
  db_data:
  mongo_data:
